server:
  port: 8081
spring:
  application:
    name: event-service
  datasource:
    url: jdbc:h2:mem:eventdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: event-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
            json:
              trusted:
                packages: com.event_booking.demo.dto